---
title: "Data Science With R"
author: "Douglas Saturnino"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    highlight: textmate
    logo: logo.png
    theme: jou
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Imports

```{r imports}
library(tidyverse)
library(janitor)
library(readr)
library(gtsummary)
library(summarytools)
library(kableExtra)
library(knitr)
library(gridExtra)
library(summarytools)
library(randomForest)
library(reshape2)
library(tidymodels)
```

# Data Collection

```{r data_collection}
df <- read_csv("datasets/train.csv")
glimpse(df)
```

# Data cleaning

```{r Data_cleaning}
df1 <- janitor::clean_names(df) %>% 
  rename(day_associated = vintage,
         health_annual_paid = annual_premium) %>% 
  mutate(
    across(where(is.character),tolower),
    driving_license = ifelse(driving_license == 1, "yes", "no"),
    previously_insured = ifelse(previously_insured == 1, "yes", "no"),
    response = ifelse(response == 1, "yes", "no"),
    vehicle_age = case_when(
      vehicle_age == "< 1 year" ~ "below_1_year",
      vehicle_age == "1-2 year" ~ "between_1_2_years",
      vehicle_age == "> 2 years" ~ "over_2_years",
    )
  ) %>% 
  mutate_if(is.character, as.factor) %>%
  mutate(response = factor(response, levels = c("yes", "no")),
       driving_license = factor(driving_license, levels = c("yes", "no")),
       previously_insured = factor(previously_insured, levels = c("yes", "no")),
       vehicle_damage = factor(vehicle_damage, levels = c("yes", "no"))
       )
glimpse(df1)

# Save df_cleaned as RDS
saveRDS(df1, "df_cleaned.rds")
```

## Data Types

```{r}
variable_class <- tibble(variables = names(df1),
      type = unlist(lapply(df1, class)))
variable_class
```

# Column Description

```{r}
variables <- df1 %>% names()
description <- c(
  "Unique ID for the customer",
  "Gender of the customer",
  "Age of the customer",
  "Customer has DL (yes/no)",
  "Unique code for the region of the customer",
  "Customer already has Vehicle Insurance (yes/no)",
  "Age of the Vehicle",
  "Customer got his/her vehicle damaged in the past (yes/no)",
  "The amount customer needs to pay as premium in the year",
  "Anonymized Code for the channel of outreaching to the customer ie. Different Agents, Over Mail, Over Phone, In Person, etc.",
  "Number of Days, Customer has been associated with the company",
  "Customer is interested in car insurance (yes/no)"
)
df_description <- tibble(variables = variables,
       description = description)

kable(df_description, format = "html") %>% 
  kable_styling(bootstrap_options = "striped",
                            full_width = FALSE)
```

# Descriptive Statics

```{r}
# Read_cleaned date
df_cleaned = readRDS("df_cleaned.rds")
```

# . Check data structure so far

```{r}
skimr::skim(df_cleaned)
```

# General overview

```{r}
df_cleaned %>% 
  select(-id) %>% 
  tbl_summary(
    type = list(response ~ "categorical",
                driving_license ~ "categorical", 
                previously_insured ~ "categorical",
                vehicle_damage ~ "categorical"),
    digits = list(all_categorical() ~ c(0, 2))
  )
```

## More detailed statistics

```{r}
num_attributes <- df_cleaned %>% 
  select(age, health_annual_paid, day_associated)

```

```{r}
descriptive_tab <- summarytools::descr(num_attributes, style = "rmarkdown") %>% round(2)


kable(data.frame(descriptive_tab), format = "html") %>% 
  kableExtra::kable_styling(bootstrap_options = "striped",
                            full_width = FALSE)
```

## VISUALIZATION

-   Numerical attributes

```{r}
# Age
age_plt = num_attributes %>% 
  ggplot(aes(x=age)) +
  geom_histogram(aes(y= after_stat(density)), binwidth = 1,
                 color= "gray", fill="lightblue", alpha=0.5)+
  geom_density(color="blue") + 
  labs(x="Ages", y="Density", title = "Customes Age Distribution") + 
  theme_minimal()

# helath_annual paid
paid_plt = num_attributes %>% 
  ggplot(aes(x=health_annual_paid)) +
  geom_histogram(aes(y= after_stat(density)), binwidth = 10000,
                 color= "gray", fill="lightblue", alpha=0.5)+
  geom_density(color="blue") + 
  labs(x="Health Annual Paid", y="Density", title = "Customes Payments Distribution") + 
  theme_minimal()

# day associated
day_plt = num_attributes %>% 
  ggplot(aes(x=day_associated)) +
  geom_histogram(aes(y= after_stat(density)),
                 color= "gray", fill="lightblue", alpha=0.5)+
  geom_density(color="blue") + 
  labs(x="Day Associated", y="Density", title = "Customes day_associated Distribution") + 
  theme_minimal()


gridExtra::grid.arrange(age_plt,paid_plt, day_plt, ncol=3)

```

-   Categoricol attributes:

```{r}
num_names <- names(num_attributes)
cat_attributes <- df_cleaned %>% 
  select(-id, -one_of(num_names))
```

```{r}
cat_attributes %>%

ggplot(aes(x=vehicle_age)) +

geom_bar(aes(fill=vehicle_age)) +

labs(x="Vehicle Age", y="Count", title = "Customes Vehicle Age") +

theme_minimal()
```

```{r}
#gender
gender_plt <- cat_attributes %>% 
  ggplot(aes(x=gender)) +
  geom_bar(aes(fill=gender)) +
  labs(x="Gender", y="Count", title = "Customes Gender") + 
  theme_minimal()

#driving_license
driving_license_plt <- cat_attributes %>% 
  ggplot(aes(x=driving_license)) +
  geom_bar(aes(fill=driving_license)) +
  labs(x="Driving License", y="Count", title = "Customes Driving Licenser") + 
  theme_minimal()

#region_code
region_code_plt <- cat_attributes %>% 
  ggplot(aes(x=region_code)) +
  geom_bar(aes(fill=factor(region_code)),
           show.legend = FALSE) +
  labs(x="Region code", y="Count", title = "Customes Region Code") + 
  theme_minimal()

#previously_insured
previously_insured_plt <- cat_attributes %>% 
  ggplot(aes(x=previously_insured)) +
  geom_bar(aes(fill=previously_insured)) +
  labs(x="Previously Insured", y="Count", title = "Customes Previously Insured") + 
  theme_minimal()

#vehicle_age
vehicle_age_plt <- cat_attributes %>% 
  ggplot(aes(x=vehicle_age)) +
  geom_bar(aes(fill=vehicle_age)) +
  labs(x="Vehicle Age", y="Count", title = "Customes Vehicle Age") + 
  theme_minimal()

#vehicle_damage
vehicle_damage_plt <- cat_attributes %>% 
  ggplot(aes(x=vehicle_damage)) +
  geom_bar(aes(fill=vehicle_damage)) +
  labs(x="Vehicle Damage", y="Count", title = "Customes Vehicle Damage") + 
  theme_minimal()

#policy_sales_channel
policy_sales_channel_plt <- cat_attributes %>% 
  ggplot(aes(x=policy_sales_channel)) +
  geom_bar(aes(fill=factor(policy_sales_channel)),
           show.legend = FALSE) +
  labs(x="Policy Sales Channel", y="Count", title = "Customes Policy Sales Channel") + 
  theme_minimal()

#response
response_plt <- cat_attributes %>% 
  ggplot(aes(x=response)) +
  geom_bar(aes(fill=response)) +
  labs(x="Response", y="Count", title = "Customes Response") + 
  theme_minimal()

gridExtra::grid.arrange(gender_plt,driving_license_plt,
                        region_code_plt, previously_insured_plt,
                        vehicle_age_plt,vehicle_damage_plt,
                        policy_sales_channel_plt, response_plt, 
                        ncol=2, nrow=4 )
```

```{r}

```
